### ISSUE TITLE
Can I attach CodeDeployServiceRole without creating it?

### ISSUE THREAD

**Issue by levichen** [davidgf/serverless-plugin-canary-deployments#35]
Hi,

Can I just attach CodeDeployServiceRole without creating it?

Because I got this error message:

```
An error occurred: CodeDeployServiceRole - API: iam:CreateRole User: arn:aws:iam::MY_ACCOUNT_ID:user/MY_USER is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::MY_ACCOUNT_ID:role/canary-deployments-test-CodeDeployServiceRole-.
```

this is my serverless.yml:
```yaml
service: canary-deployments-test

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-plugin-canary-deployments

functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: api
          method: get
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live
```
