### ISSUE TITLE
DeploymentGroup TriggerConfigurations

### ISSUE THREAD

**Issue by nason** [davidgf/serverless-plugin-canary-deployments#44]
HI thanks for this plugin! Its super cool 👍 

I'd like to setup notifications from my deploys, and think that being able to optionally pass that through config would be swell.

I think that [`buildFnDeploymentGroup`]( https://github.com/davidgf/serverless-plugin-canary-deployments/blob/master/lib/CfTemplateGenerators/CodeDeploy.js#L10) could be updated to build `TriggerConfigurations` from serverless.yml like:

```yaml
deploymentSettings:
  type: Linear10PercentEvery1Minute
  alias: Live
  preTrafficHook: preHook
  postTrafficHook: postHook
  alarms:
    - HelloFooAlarm
  triggerConfigurations:
    - 
      name: rollbacks
      events:
        - DeploymentRollback
      targetArn: !Ref SNSTopic
```

Does that make sense? Would you be open to a PR for this?
