### ISSUE TITLE
CloudFormation attached to all stages (disabled/enabled)

### ISSUE THREAD

**Issue by sdomagala** [davidgf/serverless-plugin-canary-deployments#47]
Hello,
I just found out there is an issue when trying to run this package on stage that is not whitelisted.
I have the same configuration in plugin [serverless-plugin-aws-alerts](https://github.com/ACloudGuru/serverless-plugin-aws-alerts) and as it turns out, even if alarms are not used (because stage is disabled), CloudFormation still tries to attach them to lambda.
Since alarm is not created in previous plugin based on the same check you have, CloudFormation fails to attach it.

Correct behaviour (for me) would be that if stage is disabled, all functionality of this package is disabled as well. 

I can create PR for this but first wanted to get an opinion on this, so I won't do PR that's going to be closed anyway.

Cheers

**Comment by sdomagala** [comment]
Hey, sure, I will paste the important parts:
```
service: test

frameworkVersion: ">=1.36.1"

plugins:
  - serverless-plugin-canary-deployments
  - serverless-plugin-aws-alerts

custom:
  alerts:
    stages:
      - dev
      - stage
      - prod
  deploymentSettings:
    alias: LIVE
    stages:
      - stage
      - prod

provider:
  name: aws
  runtime: nodejs8.10

functions:
  test:
    deploymentSettings:
      alarms:
        - testAlarm
    alarms:
      - functionErrors
    events:
      - http:
          path: whatever
          method: GET
```

As you can see here, alerts plugin lets you define stages it should be triggered on as well as your plugin does.
The issue is that because alarms are not created in aws-alerts plugin, canary-deployments plugin fails because even though it doesn't trigger canary deploy, it still tries to attach an alarm that doesn't exist on this stage.
Because of that I have to create alarms on dev stage as well, even though I have no use for them here.

I hope that makes sense?
