### ISSUE TITLE
alias not subscribe to sns when using arn

### ISSUE THREAD

**Issue by zjye** [davidgf/serverless-plugin-canary-deployments#54]
Sns subscription is not pointing to alias when the configuration as below
```
canarySns:
  handler: src/event/lambda.canarySns
  description: (SNS) test canary sns binding
  deploymentSettings: ${self:custom.deployment}
  events:
    - sns:
        topicName: fooTopic
        displayName: fooTopic
        filterPolicy:
          eventType:
            - FooEvent
```
