### ISSUE TITLE
Can't make it work - are there some prerequisites?

### ISSUE THREAD

**Issue by navihtot** [davidgf/serverless-plugin-canary-deployments#59]
So I tried following the readme to implement linear deployments into my existing project, and the result is, well, everything stays the same, serverless deploys everything in one go.
Are there any prerequisites, like do I need to create something manually on AWS console CodeDeploy, ...?

This is what I have in my `severless.yml`:

```
service: image-processing

plugins:
  - serverless-plugin-canary-deployments
  - serverless-plugin-scripts
  - serverless-plugin-thundra-lambda-adapters-cw
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${file(.env.${self:provider.stage}.yml):AWS_PROFILE}
  region: ${file(.env.${self:provider.stage}.yml):AWS_REGION}


  # *** IAM ROLE ***
  iamRoleStatements:
      # Code deploy permission
      - Effect: Allow
        Action:
          - codedeploy:*
        Resource:
          - "*"
...
custom:
 ...
  deploymentSettings:
    type: Linear10PercentEvery1Minute
    alias: Live
    stages:

package:
  individually: true
  exclude:
    - ./**  # Exclude all files (needed files are included later for each function)

layers:
  imageProcessing:
    path: image-processing-layer
    package:
      include:
        - "./**"
    compatibleRuntimes:
      - nodejs8.10

functions:
  image-processing:
    handler: image-processing/index.handler
    runtime: nodejs8.10
    timeout: 300
    memorySize: 256
    layers:
      - {Ref: ImageProcessingLambdaLayer}
      - arn:aws:lambda:::awslayer:AmazonLinux1803
    package:
      include:
        - image-processing/**
        - thundra_handlers/**
        - '!node_modules/**'
        - '!image-processing/node_modules/**'
        - '!image-processing/.git/**'
        - '!image-processing/test/**'
        - '!image-processing/img/**'
        - '!image-processing/coverage/**'
        - '!image-processing/.**'
        - '!image-processing/event**'
        - '!image-processing/Dockerfile'
        - '!image-processing/config_**'
        - '!image-processing/tests.js'
    events:
      - sns: ImageProcessing
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live
```

What am I doing wrong or missing?
