### ISSUE TITLE
Possible to use a generic alarm name?

### ISSUE THREAD

**Issue by jhappoldt** [davidgf/serverless-plugin-canary-deployments#66]
Thank you for this great plugin!

I've successfully used the plugin to configure canary deployments using the example format in the README.md.  This works well but becomes very verbose when configuring multiple alarms for hundreds of lambda functions.

We create standard alarms (Error, Duration, Throttles) using the https://github.com/ACloudGuru/serverless-plugin-aws-alerts plugin.

Currently every function has a deployment block like the following:

```
...standard function config...
    deploymentSettings:
      alias: live
      type: Linear10PercentEvery1Minute
      alarms:
        - <Function_Name>FunctionErrorsAlarm
        - <Function_Name>FunctionDurationAlarm
        - <Function_Name>FunctionThrottlesAlarm
```
This is a highly manual and error prone process as the names must match exactly.  Is making the alarm binding automatic possible?  If not, would you be willing to accept a PR that added this functionality?

Thanks!
