### ISSUE TITLE
Serveless deploy don't adds lambda permissions to alias

### ISSUE THREAD

**Issue by levkaganv** [davidgf/serverless-plugin-canary-deployments#71]
# Bug Report

## Description

After updating to serverless 1.60.4 (from 1.37.1) deployed stack started to return `{"message": "Internal server error"}` for all calls.  

Tried to run "test" from AWS APIGW "Resources"->"Method" view and got: `Thu Dec 26 11:52:32 UTC 2019 : Execution failed due to configuration error: Invalid permissions on Lambda function`

Rolled back to 1.37.1 and deploy worked fine.

After some digging in cloud trails found that serveless 1.60.4 didn't give permissions to the "alias" version of our lambda:

![Screen Shot 2019-12-26 at 1 37 35 PM](https://user-images.githubusercontent.com/41537091/71475092-68f47000-27e7-11ea-98c4-4902444e0b96.png)

## Setup info (parts I thought are relevant):
```yaml
plugins:
  - serverless-plugin-canary-deployments

provider:
  name: aws
  runtime: python3.6

functions:
  - app:
      handler: wsgi_handler.handler
      timeout: 30
      deploymentSettings:
        type: AllAtOnce
        postTrafficHook: tests
        alias: live
```
