### ISSUE TITLE
Hook functions don't have permission to set deployment status

### ISSUE THREAD

**Issue by samhanes-fs** [davidgf/serverless-plugin-canary-deployments#93]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a function with `deploymentSettings` including a `preTrafficHook`:
```yaml
functions:
  http:
    handler: dist/lambda/http.http
    events:
      - httpApi: '*'
    deploymentSettings:
      type: AllAtOnce
      alias: Live
      preTrafficHook: deployPreTraffic

  deployPreTraffic:
    handler: dist/lambda/deploy.preTraffic
    timeout: 300 # 5m
```
2. Make `deployPreTraffic` notify CodeDeploy of success:
```javascript
const { CodeDeploy } = require('aws-sdk');
const codeDeploy = new CodeDeploy({ apiVersion: "2014-10-06" });

module.exports.preTraffic = async (event) => {
  await codeDeploy
    .putLifecycleEventHookExecutionStatus({
      deploymentId: event.DeploymentId,
      lifecycleEventHookExecutionId: event.LifecycleEventHookExecutionId,
      status: "Succeeded",
    })
    .promise();
};
```
3. Deploy the application
4. Check the logs of the `deployPreTraffic` function

What happens?
-------------

The `deployPreTraffic` function fails because the Serverless-generated Lambda execution role doesn't grant it permission to set the deployment status. The CodeDeploy hook therefore times out after an hour and the deployment fails.

What were you expecting to happen?
----------------------------------

The Serverless-generated Lambda execution role should automatically include permission for the deployment hook functions to update the deployment status. The deployment with hook functions should work with no extra IAM configuration.

Any logs, error output, etc?
----------------------------

```plain
AccessDeniedException: User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/xxxx-api-production-us-west-2-lambdaRole/xxxx-api-production-deployPreTraffic is not authorized to perform: codedeploy:PutLifecycleEventHookExecutionStatus on resource: arn:aws:codedeploy:us-west-2:xxxxxxxxxxxx:deploymentgroup:xxxx-api-production-XXXXapiproductionDeploymentApplication-XXXXXXXXXXXX/xxxx-api-production-HttpLambdaFunctionDeploymentGroup-XXXXXXXXXXXX
```

Any other comments?
-------------------

It's possible to work around this issue by manually adding the relevant permissions in `serverless.yml`:
```yaml
provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'codedeploy:PutLifecycleEventHookExecutionStatus'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:codedeploy:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':deploymentgroup:'
            - Ref: XXXXapiproductionDeploymentApplication
            - '/*'
```

What versions of software are you using?
----------------------------------------

```plain
serverless: 1.78.1
serverless-plugin-canary-deployments: 0.4.8
```
